spring.application.name=SSOProjectProvidingAccessToken

# Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=sritam
spring.datasource.password=lion

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Authorization uri
oauth2.authorization-base-url=/oauth2/authorization/

server.port=4041